### ISSUE TITLE
Prepare rest api

### ISSUE THREAD

**Issue by KrzysiekWyka** [leocode/image-service#1]
We should create rest api to integrate with our wrappers/adapters. As a library, my recommendation is to use fastify (@soanvig used it in puppeteer-service and told that is very easy and has a built-in validator).

### Endpoints to create:

`POST /image/metadata`
`POST /video/metadata`
`POST /image/:adapter/crop`
`POST /image/:adapter/resize`
`POST /video/:adapter/resize`

`adapter` param should be validated, available values will be defined in some const.

### TODO:
* Setup fastify
* Register first handlers (at this point simply throw some "Not implemented" error)
* Create Dockerfile

**Comment by soanvig** [comment]
`POST /image/:adapter/cut` -> `crop` I guess

**Comment by KrzysiekWyka** [comment]
> `POST /image/:adapter/cut` -> `crop` I guess

Updated
